services:
  - type: web
    name: autoops-engine
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CPU_THRESHOLD
        value: "85"
      - key: RAM_THRESHOLD
        value: "90"
      - key: DISK_THRESHOLD
        value: "90"
